In [1]:
import numpy as np
a=np.random.randint(1,100,size=(3,4))
print(a)

[[42 92 49 47]
 [80  3 49 37]
 [12 62 80 11]]


In [11]:
print(np.max(a))
##Column wise maximum
print(np.max(a,axis=0))
##row wise maximum
print(np.max(a,axis=1))


92
[80 92 80 47]
[92 80 80]


In [10]:
print(np.min(a))
##Column wise minimum
print(np.min(a,axis=0))
##row wise minimum
print(np.min(a,axis=1))

3
[12  3 49 11]
[42  3 11]


In [7]:
print(np.sum(a))
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))


564
[230 169 165]
[134 157 178  95]


In [8]:
np.sort(a)

array([[42, 47, 49, 92],
       [ 3, 37, 49, 80],
       [11, 12, 62, 80]])

In [9]:
np.sort(a,axis=0)

array([[12,  3, 49, 11],
       [42, 62, 49, 37],
       [80, 92, 80, 47]])

In [18]:
##M.IMP in exam......................
a=np.array([[15,10,14],[20,22,25],[10,8,9],[7,10,12]])
print(a)

[[15 10 14]
 [20 22 25]
 [10  8  9]
 [ 7 10 12]]


In [20]:
##continue
b=list(a)
b.sort(key=lambda x:x[-1])
print(np.array(b))

[[10  8  9]
 [ 7 10 12]
 [15 10 14]
 [20 22 25]]


In [22]:
np.argsort(a[:,-1])
a[np.argsort(a[:,-1])]

array([[10,  8,  9],
       [ 7, 10, 12],
       [15, 10, 14],
       [20, 22, 25]])

In [28]:
a=np.arange(1,13).reshape(3,4)
b=np.arange(13,25).reshape(3,4)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [29]:
c=np.sum(a,axis=1)
print(c)

[10 26 42]


In [31]:
d=np.concatenate((a,c.reshape(3,-1)),axis=1)
print(d)

[[ 1  2  3  4 10]
 [ 5  6  7  8 26]
 [ 9 10 11 12 42]]


In [32]:
##next prgrm
a=np.array([[1,5,7],[2,5,1],[1,8,1]])
print(a)

[[1 5 7]
 [2 5 1]
 [1 8 1]]


In [33]:
np.where(a==1)

(array([0, 1, 2, 2], dtype=int64), array([0, 2, 0, 2], dtype=int64))

In [34]:
np.where(a==1,100,0)

array([[100,   0,   0],
       [  0,   0, 100],
       [100,   0, 100]])

In [35]:
##TASK for knowledge till 41
a=np.array([[30,20,40],[50,60,70],[10,30,50]])
print(a)

[[30 20 40]
 [50 60 70]
 [10 30 50]]


In [36]:
np.where(a>50,1,np.where(a>30,2,3))


array([[3, 3, 2],
       [2, 1, 1],
       [3, 3, 2]])

In [38]:
x=np.arange(1,13)
np.array_split(x,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [39]:
np.array_split(x,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [40]:
np.array_split(x,5)

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [41]:
np.array_split(x,15)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [43]:
y=np.arange(1,13).reshape(3,4)
np.array_split(y,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [44]:
y=np.arange(1,13).reshape(3,4)
np.array_split(y,3,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [45]:
np.array_split(y,4,axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [47]:
##IMP FOR EXAM do add,sub,mut,transpose
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [49]:
##addition
c=np.dot(a,b)
d=a.T
e=b.T
print(c)
print(d)
print(e)


[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 13 16]
 [11 14 17]
 [12 15 18]]


In [ ]:
##if polymorphism
def __add__(self,other)
return self.array